MuseumApp/urls.py
"""URLs of MuseumApp."""
from django.urls import path

from .views import (
    FloorListView, ExpositionListView, ExhibitView,
    ExpositionCreationView, ExpositionUpdateView, ExpositionDeleteView,
    ExhibitCreationView, ExhibitUpdateView, ExhibitDeleteView,
    ProfileView, edit_profile
)

app_name = 'museum'

urlpatterns = [
    path(
        'floor/<int:floor_level>/',
        FloorListView.as_view(),
        name='floor'
    ),
    path(
        'exposition/<int:exposition_pk>/',
        ExpositionListView.as_view(),
        name='exposition'
    ),
    path(
        'exposition/create/',
        ExpositionCreationView.as_view(),
        name='exposition_create'
    ),
    path(
        'exposition/update/<int:exposition_pk>/',
        ExpositionUpdateView.as_view(),
        name='exposition_update'
    ),
    path(
        'exposition/delete/<int:exposition_pk>/',
        ExpositionDeleteView.as_view(),
        name='exposition_delete'
    ),
    path(
        'exhibit/<int:exhibit_pk>/',
        ExhibitView.as_view(),
        name='exhibit'
    ),
    path(
        'exhibit/create/',
        ExhibitCreationView.as_view(),
        name='exhibit_create'
    ),
    path(
        'exhibit/update/<int:exhibit_pk>/',
        ExhibitUpdateView.as_view(),
        name='exhibit_update'
    ),
    path(
        'exhibit/delete/<int:exhibit_pk>/',
        ExhibitDeleteView.as_view(),
        name='exhibit_delete'
    ),
    path(
        'profile/edit/',
        edit_profile,
        name='edit_profile'
    ),
    path(
        'profile/<str:username>/',
        ProfileView.as_view(),
        name='profile'
    ),
]

PagesApp/urls.py
"""URLs of PagesApp."""
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('rules/', views.RulesView.as_view(), name='rules'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView

handler403 = 'PagesApp.views.page_403'
handler404 = 'PagesApp.views.page_404'
handler500 = 'PagesApp.views.page_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PagesApp.urls')),
    path('museum/', include('MuseumApp.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PagesApp/models.py
from django.db import models

# Create your models here.

PagesApp/views.py
"""Views of PagesApp."""
from django.shortcuts import render
from django.views.generic import TemplateView


class AboutView(TemplateView):
    template_name = 'PagesApp/about.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['is_admin'] = self.request.user.groups.filter(
            name__in=['admin']
        ).exists()

        return context


class RulesView(TemplateView):
    template_name = 'PagesApp/rules.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['is_admin'] = self.request.user.groups.filter(
            name__in=['admin']
        ).exists()

        return context


class IndexView(TemplateView):
    template_name = 'PagesApp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['is_admin'] = self.request.user.groups.filter(
            name__in=['admin']
        ).exists()

        return context


def page_403(request, reason=""):
    """Custom 403 page."""
    return render(request, 'PagesApp/403csrf.html', status=403)


def page_404(request, exception):
    """Custom 404 page."""
    return render(request, 'PagesApp/404.html', status=404)


def page_500(request):
    """Custom 500 page."""
    return render(request, 'PagesApp/500.html', status=500)

templates/PagesApp/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка CSRF токена{% endblock %}
{% block content %}
  <h1>Ошибка CSRF токена. 403</h1>
  <a href="{% url 'blog:index' %}">Вернуться на главную</a>
{% endblock %}

templates/PagesApp/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        О проекте
      </div>
      <div class="card-body">
        <p>
          Добро пожаловать в онлайн музей — уникальное виртуальное пространство, где культура и технологии соединяются, чтобы подарить вам незабываемый опыт знакомства с искусством со всего мира. 
        </p>
        <p>
          Наш музей предлагает разнообразные виртуальные выставки, охватывающие различные эпохи и стили. Вы сможете погрузиться в мир классического искусства, современного дизайна, графики и фотографии. Каждая выставка сопровождается подробными описаниями, аудиогидами и видеоматериалами, которые помогут глубже понять контекст и значение представленных работ.
        </p>
        <p>
          Мы используем передовые технологии, чтобы сделать ваше взаимодействие с искусством максимально увлекательным. Вы можете участвовать в виртуальных турах по нашему сайту.
        </p>
        <p>
          Присоединяйтесь к нашему сообществу любителей искусства!
        </p>
      </div>
    </div>
  </div>
{% endblock %}

templates/PagesApp/index.html
{% extends "base.html" %}
{% block title %}
  Главная
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Главная
      </div>
      <div class="card-body">
        <a class="navbar-brand text-primary" href="{% url 'museum:floor' 1 %}">
          Прогуляться по 1 этажу
        </a>
        <br>
        <a class="navbar-brand text-primary" href="{% url 'museum:floor' 2 %}">
          Прогуляться по 2 этажу
        </a>
        <br>
        <a class="navbar-brand text-primary" href="{% url 'museum:floor' 3 %}">
          Прогуляться по 3 этажу
        </a>
      </div>
    </div>
  </div>
{% endblock %}

templates/PagesApp/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Правила сайта
      </div>
      <div class="card-body">
        <p>
          <b>Соблюдение авторских прав</b> Не используйте и не
          распространяйте материалы музея без разрешения.
          Уважайте права художников и авторов.
        </p>
        <p>
          <b>Технические рекомендации</b> Перед посещением
          виртуальных выставок убедитесь, что ваше устройство
          соответствует техническим требованиям для оптимального
          просмотра.
        </p>
      </div>
    </div>
  </div>
{% endblock %}