MuseumApp/urls.py
"""URLs of MuseumApp."""
from django.urls import path

from .views import (
    FloorListView, ExpositionListView, ExhibitView,
    ExpositionCreationView, ExpositionUpdateView, ExpositionDeleteView,
    ExhibitCreationView, ExhibitUpdateView, ExhibitDeleteView,
    ProfileView, edit_profile
)

app_name = 'museum'

urlpatterns = [
    path(
        'floor/<int:floor_level>/',
        FloorListView.as_view(),
        name='floor'
    ),
    path(
        'exposition/<int:exposition_pk>/',
        ExpositionListView.as_view(),
        name='exposition'
    ),
    path(
        'exposition/create/',
        ExpositionCreationView.as_view(),
        name='exposition_create'
    ),
    path(
        'exposition/update/<int:exposition_pk>/',
        ExpositionUpdateView.as_view(),
        name='exposition_update'
    ),
    path(
        'exposition/delete/<int:exposition_pk>/',
        ExpositionDeleteView.as_view(),
        name='exposition_delete'
    ),
    path(
        'exhibit/<int:exhibit_pk>/',
        ExhibitView.as_view(),
        name='exhibit'
    ),
    path(
        'exhibit/create/',
        ExhibitCreationView.as_view(),
        name='exhibit_create'
    ),
    path(
        'exhibit/update/<int:exhibit_pk>/',
        ExhibitUpdateView.as_view(),
        name='exhibit_update'
    ),
    path(
        'exhibit/delete/<int:exhibit_pk>/',
        ExhibitDeleteView.as_view(),
        name='exhibit_delete'
    ),
    path(
        'profile/edit/',
        edit_profile,
        name='edit_profile'
    ),
    path(
        'profile/<str:username>/',
        ProfileView.as_view(),
        name='profile'
    ),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView

handler403 = 'PagesApp.views.page_403'
handler404 = 'PagesApp.views.page_404'
handler500 = 'PagesApp.views.page_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PagesApp.urls')),
    path('museum/', include('MuseumApp.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MuseumApp/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class AbstractFieldsModel(models.Model):
    """Abstract model to inherit description and title fields\n"""

    title = models.CharField(
        verbose_name='Заголовок',
        max_length=256
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    def __str__(self) -> str:
        return self.title

    class Meta():
        abstract = True


class Exposition(AbstractFieldsModel):
    """Exposition model has basic fields. Considered to be\n
     Model for all Expostions local (choice 1-3) and locations\n
     like other museums (choice -1) and storage unit (choice 0)\n"""

    POSITION_CHOICES = {
        0: "Запасник",
        1: "Первый этаж",
        2: "Второй этаж",
        3: "Третий этаж",
        4: "Другой музей"
    }

    position = models.SmallIntegerField(
        verbose_name='Размещение',
        choices=POSITION_CHOICES,
        default=POSITION_CHOICES.get(-1)
    )

    on_restoration = models.BooleanField(
        verbose_name='На рестоврации',
        default=False
    )

    open = models.BooleanField(
        verbose_name='Открыта',
        default=False
    )

    @classmethod
    def get_default(cls):
        storage, created = cls.objects.get_or_create(
            title='Запансник музея',
            description="""Запасник музея специально
             предназначенный для хранения экспонатов.
             ВНИМАНИЕ!!! Данная модель не удаляемая,
             она будет восстанавливаться в целях
             сохранения работы данной системы!""",
            position=0
        )
        return storage

    def save(self, *args, **kwargs):  # save method override
        if self.on_restoration:
            self.open = False
        super(Exposition, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return f'museum/exposition/{self.pk}/'

    class Meta():
        verbose_name = 'экспозиция'
        verbose_name_plural = 'Экспозиции'


class Exhibit(AbstractFieldsModel):
    """Exhibit model has basic fields. Could be placed in\n
     expostion, storage or send to be restored using field\n
     location\n"""

    placement = models.ForeignKey(
        to=Exposition,
        on_delete=models.SET_DEFAULT,
        default=Exposition.get_default,
        related_name='exhibit'
    )

    image = models.ImageField(
        verbose_name='Изображение',
        upload_to="media/",
        null=True,
        blank=True
    )

    def get_absolute_url(self):
        return f'museum/exhibit/{self.pk}/'

    class Meta():
        verbose_name = 'экспонат'
        verbose_name_plural = 'Экспонаты'

MuseumApp/forms.py
from django import forms
from .models import User


class ProfileEditForm(forms.ModelForm):

    class Meta():
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'username',
        )

MuseumApp/views.py
"""Views of MuseumApp."""
from django.shortcuts import (
    render, redirect,
    get_object_or_404
)
from django.http import Http404
from django.db.models import Count
from django.views.generic import (
    DetailView, ListView,
    CreateView, DeleteView, UpdateView
)
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Exposition, Exhibit, User
from .forms import ProfileEditForm
# Create your views here.


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class FloorListView(ListView):

    template_name = 'MuseumApp/floor.html'
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        """Will be loaded 5th.\n"""

        selected_floor = self.kwargs['floor_level']
        user = self.request.user
        possible = user.groups.filter(name__in=['admin']).exists()

        if selected_floor in [-1, 0] and not possible:
            """Acctualy it exist but they are not allowed to visit it.\n"""
            raise Http404(f"Данный этаж ({selected_floor}) не существует")

        if selected_floor not in Exposition.POSITION_CHOICES.keys():
            raise Http404("Данный этаж не существует")

        page_obj = Exposition.objects.filter(
            position=selected_floor,
            on_restoration=False,
            open=True
        ).annotate(exibits_count=Count("exhibit"))

        return page_obj

    def get_context_data(self, *args, **kwargs):
        """Will be loaded 7th. So there is no actual need to check floor\n
         existence second time\n"""

        context = super().get_context_data(*args, **kwargs)

        context['floor_level'] = Exposition.POSITION_CHOICES[
            self.kwargs['floor_level']
        ]
        context['is_admin'] = self.request.user.groups.filter(
            name__in=['admin']
        ).exists()

        return context


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class ExpositionListView(ListView):

    template_name = 'MuseumApp/exposition.html'
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        """Will be loaded 5th.\n"""

        user = self.request.user
        possible = user.groups.filter(name__in=['admin']).exists()

        selected_exp = get_object_or_404(
            Exposition,
            pk=self.kwargs['exposition_pk']
        )

        if not selected_exp.open and not possible:
            raise Http404(f"""Данная экспозиция ({selected_exp.pk})
                не существует""")

        page_obj = selected_exp.exhibit.all()

        return page_obj

    def get_context_data(self, *args, **kwargs):
        """Will be loaded 7th. So there is no actual need to check exposition\n
         existence second time\n"""

        context = super().get_context_data(*args, **kwargs)

        selected_exp = get_object_or_404(
            Exposition,
            pk=self.kwargs['exposition_pk']
        )

        context['exposition'] = selected_exp
        context['is_admin'] = self.request.user.groups.filter(
            name__in=['admin']
        ).exists()

        return context


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class ExpositionCreationView(CreateView):
    model = Exposition
    fields = [
        "title",
        "description",
        "position",
        "on_restoration",
        "open"
    ]

    def get_context_data(self, **kwargs):

        user = self.request.user
        possible = user.groups.filter(name__in=['admin']).exists()

        if not possible:
            raise Http404("Данная страница не существует")

        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        self.object = form.save()
        return redirect('museum:exposition', exposition_pk=self.object.pk)


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class ExpositionUpdateView(UpdateView):
    model = Exposition
    pk_url_kwarg = 'exposition_pk'
    fields = [
        "title",
        "description",
        "position",
        "on_restoration",
        "open"
    ]

    def get_context_data(self, **kwargs):

        user = self.request.user
        possible = user.groups.filter(name__in=['admin']).exists()

        if not possible:
            raise Http404("Данная страница не существует")

        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        self.object = form.save()
        return redirect('museum:exposition', exposition_pk=self.object.pk)


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class ExpositionDeleteView(DeleteView):
    model = Exposition
    pk_url_kwarg = 'exposition_pk'
    fields = [
        "title",
        "description",
        "position",
        "on_restoration",
        "open"
    ]

    def get_context_data(self, **kwargs):

        user = self.request.user
        possible = user.groups.filter(name__in=['admin']).exists()

        if not possible:
            raise Http404("Данная страница не существует")

        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        floor = self.object.position

        self.object.delete()

        return redirect('museum:floor', floor_level=floor)


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class ExhibitView(DetailView):

    model = Exhibit
    template_name = 'MuseumApp/exhibit.html'
    pk_url_kwarg = 'exhibit_pk'

    def get_context_data(self, *args, **kwargs):

        context = super().get_context_data(*args, **kwargs)

        selected_exh = get_object_or_404(
            Exhibit,
            pk=self.kwargs['exhibit_pk']
        )

        context['exhibit'] = selected_exh
        context['is_admin'] = self.request.user.groups.filter(
            name__in=['admin']
        ).exists()

        return context


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class ExhibitCreationView(CreateView):
    model = Exhibit
    fields = [
        "title",
        "description",
        "placement",
        "image"
    ]

    def get_context_data(self, **kwargs):

        user = self.request.user
        possible = user.groups.filter(name__in=['admin']).exists()

        if not possible:
            raise Http404("Данная страница не существует")

        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        self.object = form.save()
        return redirect('museum:exhibit', exhibit_pk=self.object.pk)


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class ExhibitUpdateView(UpdateView):
    model = Exhibit
    pk_url_kwarg = 'exhibit_pk'
    fields = [
        "title",
        "description",
        "placement",
        "image"
    ]

    def get_context_data(self, **kwargs):

        user = self.request.user
        possible = user.groups.filter(name__in=['admin']).exists()

        if not possible:
            raise Http404("Данная страница не существует")

        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        self.object = form.save()
        return redirect('museum:exhibit', exhibit_pk=self.object.pk)


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class ExhibitDeleteView(DeleteView):
    model = Exhibit
    pk_url_kwarg = 'exhibit_pk'
    fields = [
        "title",
        "description",
        "placement",
        "image"
    ]

    def get_context_data(self, **kwargs):

        user = self.request.user
        possible = user.groups.filter(name__in=['admin']).exists()

        if not possible:
            raise Http404("Данная страница не существует")

        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        exposition = self.object.placement

        self.object.delete()

        return redirect('museum:exposition', exposition_pk=exposition.pk)


@method_decorator(login_required(login_url='/auth/login/'), name="dispatch")
class ProfileView(DetailView):
    model = User
    template_name = 'MuseumApp/profile.html'

    def get_object(self, queryset=None):
        return get_object_or_404(User, username=self.kwargs['username'])

    def get_context_data(self, *args, **kwargs):

        context = super().get_context_data(*args, **kwargs)

        context['is_admin'] = context['object'].groups.filter(
            name__in=['admin']
        ).exists()

        return context


@login_required(login_url='/auth/login/')
def edit_profile(request):
    """Profile view."""
    profile = request.user
    form = ProfileEditForm(
        request.POST,
        instance=profile
    )
    context = {
        'profile': profile,
        'form': form,
    }
    if form.is_valid():
        new_info = form.save(commit=False)
        profile.first_name = new_info.first_name
        profile.last_name = new_info.last_name
        profile.email = new_info.email
        profile.username = new_info.username
        profile.save()
        return redirect('museum:profile', profile.username)

    return render(request, 'MuseumApp/user.html', context)

templates/MuseumApp/exhibit.html
{% extends "base.html" %}
{% block title %}
  {{ object.title }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if object.image %}
          <a href="{{ object.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ object.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{object.placement.title}}: {{ object.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if object.placement.on_restoration %}
              <p class="text-danger">Экспозиция на рестоврации</p>
            {% elif not object.placement.open %}
              <p class="text-danger">Экспозиция закрыта</p>
            {% endif %}
          </small>
        </h6>
        <p class="card-text">{{ object.description|linebreaksbr }}</p>
        {% if is_admin %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'museum:exhibit_update' object.pk %}" role="button">
              Редактировать экспонат
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'museum:exhibit_delete' object.pk %}" role="button">
              Удалить экспонат
            </a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/MuseumApp/exhibit_confirm_delete.html
{% extends "base.html" %}
{% block title %}
    Удаление экспоната '{{ object.title }}'
{% endblock %}
{% block content %}
    <h1 class="text-center">Удаление экспоната '{{ object.title }}'</h1>
    <p class="col-6 offset-3 mb-5 lead text-center">Вы уверены в удалении экспоната pk='{{ object.pk }}'?</p>
    <form method="post">{% csrf_token %}
        {{ form }}
        <div class = "d-flex justify-content-center">
            <input type="submit" value="Confirm" class="btn btn-danger">
        </div>
    </form>
{% endblock %}

templates/MuseumApp/exhibit_form.html
{% extends "base.html" %}
{% block title %}
    Добавление экспоната
{% endblock %}
{% block content %}
    <h1 class="text-center">Добавление экспоната</h1>
    <p class="col-6 offset-3 mb-5 lead text-center">Заполните форму ниже и добвьте новый  экспонат</p>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" class="btn btn-primary">
    </form>
{% endblock %}

templates/MuseumApp/exposition.html
{% extends "base.html" %}
{% block title %}
  Экспозиция {{ exposition.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Экспозиция {{ exposition.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ exposition.description }}</p>
  {% if is_admin %}
    <div class = "d-flex justify-content-center">
      <button type="button" class="btn btn-warning btn-lg btn-block"><a class="text-decoration-none text-reset"
        href="{% url 'museum:exposition_update' exposition.pk %}">Редактировать экспозицию</a></button>
      <button type="button" class="btn btn-danger btn-lg btn-block"><a class="text-decoration-none text-reset"
        href="{% url 'museum:exposition_delete' exposition.pk %}">Удалить экспозицию</a></button>
    </div>
  {% endif %}
  {% for exhibit in page_obj %}
    <article class="mb-5">  
      {% include "includes/exhibit_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/MuseumApp/exposition_confirm_delete.html
{% extends "base.html" %}
{% block title %}
    Удаление экспозиции '{{ object.title }}'
{% endblock %}
{% block content %}
    <h1 class="text-center">Удаление экспозиции '{{ object.title }}'</h1>
    <p class="col-6 offset-3 mb-5 lead text-center">Вы уверены в удалении экспозиции pk='{{ object.pk }}'?</p>
    <form method="post">{% csrf_token %}
        {{ form }}
        <div class = "d-flex justify-content-center">
            <input type="submit" value="Confirm" class="btn btn-danger">
        </div>
    </form>
{% endblock %}

templates/MuseumApp/exposition_form.html
{% extends "base.html" %}
{% block title %}
    {% with request.resolver_match.view_name as view_name %}
        {% if view_name == 'museum:exposition_create' %} Добавление экспозициии {% elif view_name == 'museum:exposition_update' %} Редактирование экспозициии {{ object.pk }} {% endif %}
    {% endwith %}
{% endblock %}
{% block content %}
    {% with request.resolver_match.view_name as view_name %}
        {% if view_name == 'museum:exposition_create' %}
            <h1 class="text-center">Добавление экспозициии</h1>
            <p class="col-6 offset-3 mb-5 lead text-center">Заполните форму ниже и добвьте новую экспозициию</p>
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" class="btn btn-primary">
            </form>
        {% elif view_name == 'museum:exposition_update' %}
            <h1 class="text-center">Редактирование экспозициии "{{ object.title }}"</h1>
            <p class="col-6 offset-3 mb-5 lead text-center">Заполните форму ниже и измените экспозициию с pk={{ object.pk }}</p>
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Update" class="btn btn-primary">
            </form>
        {% endif %}
    {% endwith %}
{% endblock %}

templates/MuseumApp/floor.html
{% extends "base.html" %}
{% block title %}
  Этаж {{ floor_level }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Добро пожаловать на этаж "{{ floor_level }}"</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">Это один из трёх этажей нашего музея!</p>
  {% if is_admin %}
    <div class = "d-flex justify-content-center">
      <button type="button" class="btn btn-primary btn-lg btn-block"><a class="text-decoration-none text-reset"
        href="{% url 'museum:exposition_create' %}">Добавить экспозицию</a></button>
    </div>
  {% endif %}
  {% for exposition in page_obj %}
    <article class="mb-5">  
      {% include "includes/exposition_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/MuseumApp/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ profile.username }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ object.username }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Имя пользователя: {% if object.get_full_name %}{{ object.get_full_name }}{% else %} не указано {% endif %}</li>
      <li class="list-group-item text-muted">Роль: {% if is_admin %}Админ{% else %}Пользователь{% endif %}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == object %}
      <a class="btn btn-sm text-muted" href="{% url 'museum:edit_profile' %}">Редактировать профиль</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
      {% endif %}
    </ul>
  </small>
  <br>
{% endblock %}

templates/MuseumApp/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user.username }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}