MuseumApp/urls.py
"""URLs of MuseumApp."""
from django.urls import path

from .views import (
    FloorListView, ExpositionListView, ExhibitView,
    ExpositionCreationView, ExpositionUpdateView, ExpositionDeleteView,
    ExhibitCreationView, ExhibitUpdateView, ExhibitDeleteView,
    ProfileView, edit_profile
)

app_name = 'museum'

urlpatterns = [
    path(
        'floor/<int:floor_level>/',
        FloorListView.as_view(),
        name='floor'
    ),
    path(
        'exposition/<int:exposition_pk>/',
        ExpositionListView.as_view(),
        name='exposition'
    ),
    path(
        'exposition/create/',
        ExpositionCreationView.as_view(),
        name='exposition_create'
    ),
    path(
        'exposition/update/<int:exposition_pk>/',
        ExpositionUpdateView.as_view(),
        name='exposition_update'
    ),
    path(
        'exposition/delete/<int:exposition_pk>/',
        ExpositionDeleteView.as_view(),
        name='exposition_delete'
    ),
    path(
        'exhibit/<int:exhibit_pk>/',
        ExhibitView.as_view(),
        name='exhibit'
    ),
    path(
        'exhibit/create/',
        ExhibitCreationView.as_view(),
        name='exhibit_create'
    ),
    path(
        'exhibit/update/<int:exhibit_pk>/',
        ExhibitUpdateView.as_view(),
        name='exhibit_update'
    ),
    path(
        'exhibit/delete/<int:exhibit_pk>/',
        ExhibitDeleteView.as_view(),
        name='exhibit_delete'
    ),
    path(
        'profile/edit/',
        edit_profile,
        name='edit_profile'
    ),
    path(
        'profile/<str:username>/',
        ProfileView.as_view(),
        name='profile'
    ),
]

PagesApp/urls.py
"""URLs of PagesApp."""
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('rules/', views.RulesView.as_view(), name='rules'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView

handler403 = 'PagesApp.views.page_403'
handler404 = 'PagesApp.views.page_404'
handler500 = 'PagesApp.views.page_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PagesApp.urls')),
    path('museum/', include('MuseumApp.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/category_link.html
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  {{ post.category.title }}
</a>

templates/includes/exhibit_card.html
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if exibit.image %}
          <a href="{{ exhibit.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ exibit.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ exhibit.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if exhibit.placement.on_restoration %}
              <p class="text-danger">Экспозиция на рестоврации</p>
            {% elif not exhibit.placement.open %}
              <p class="text-danger">Экспозиция закрыта</p>
            {% endif %}
          </small>
        </h6>
        <p class="card-text">{{ exhibit.description|truncatewords:10 }}</p>
        <a href="{% url 'museum:exhibit' exhibit.id %}" class="card-link">Узнать больше об экспонате</a>
      </div>
    </div>
  </div>

templates/includes/exposition_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      {% if exposition.image %}
        <a href="{{ post.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
        </a>
      {% endif %}
      <h5 class="card-title">{{ exposition.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {% if exposition.on_restoration %}
            <p class="text-danger">Экспозиция на рестоврации</p>
          {% elif not exposition.open %}
            <p class="text-danger">Экспозиция закрыта</p>
          {% endif %}
        </small>
      </h6>
      <p class="card-text">Экспозиция состоит из {{ exposition.exibits_count}} экспонатов</p>
      <p class="card-text">{{ exposition.description|truncatewords:10 }}</p>
      <a href="{% url 'museum:exposition' exposition.id %}" class="card-link">Узнать больше об экспозции</a>
    </div>
  </div>
</div>

templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Музей</p>
</footer>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: #2b2c2b">
    <div class="container">
      <a class="navbar-brand text-white" href="{% url 'pages:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Музей
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:about' %} text-white {% endif %}" href="{% url 'pages:about' %}">
              О музее
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:rules' %} text-white {% endif %}" href="{% url 'pages:rules' %}">
              Правила
            </a>
          </li>
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              {% if is_admin %}
                <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                    href="{% url 'museum:exhibit_create' %}">Добавить экспонат</a></button>
              {% endif %}
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'museum:profile' user.username %}">{{ user.username }}</a></button>
              <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary"><a class="text-decoration-none text-reset">Выйти</a></button>
              </form>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'login' %}">Войти</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'registration' %}">Регистрация</a></button>
            </div>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}